apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: premgowda07/simple-flask-app:latest   # Make sure you replace this with your Docker Hub image if pushing to Docker Hub
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
