apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  selector:
    app: simple-flask-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 5000   # Port in the container
  type: LoadBalancer

